version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    tty: true
    ports:
      - "3200:3000"
    environment:
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file: .env
    # ネットワーク
    networks:
      - default
volumes:
  node_modules: # ネットワーク
networks:
  default:
    driver: bridge
