version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    tty: true
    ports:
      - "3200:3000"
    environment:
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file: .env
    # ネットワーク
    networks:
      - default
  web:
    image: nginx:alpine
    ports:
      - 8888:80
    privileged: true
    volumes:
      - "./site:/usr/share/nginx/html"
    # ネットワーク
    networks:
      - default
    # If you want to run `yarn dev` at docker compose startup
    # command: sh -c "yarn dev"
volumes:
  node_modules: # ネットワーク
networks:
  default:
    driver: bridge
